package com.bt.orchestration.ingest.entity;

import java.io.Serializable;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.bt.orchestration.ingest.converters.ItemDetailsConverter;
import com.bt.orchestration.ingest.converters.ListMapConverter;
import com.bt.orchestration.ingest.model.ItemDetails;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "OrderStatus")
public class OrderStatus implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 3791224874074298762L;

	@DynamoDBHashKey(attributeName = "CartId")
    private String orderId;
    
    @DynamoDBAttribute(attributeName = "Status")
    private String status;
    
    @DynamoDBAttribute(attributeName = "ItemDetails")
    @DynamoDBTypeConverted(converter = ItemDetailsConverter.class)
    private List<ItemDetails> itemDetails;
}
