package com.bt.orchestration.ingest.entity;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "WorkflowTracker")
public class WorkflowTracker implements Serializable{

	@DynamoDBHashKey(attributeName = "TrackerId")
	@DynamoDBAutoGeneratedKey
    private String trackerId;
	
	@DynamoDBAttribute(attributeName = "CartId")
    private String orderId;
    
    @DynamoDBAttribute(attributeName = "ItemId")
    private String itemId;

    @DynamoDBAttribute(attributeName = "Status")
    private String eventStatus;
    
    @DynamoDBAttribute(attributeName = "Quantity")
    private String quantity;
}
