package com.bt.orchestration.conductoringestservice.model;

import java.io.Serializable;
import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.bt.orchestration.conductoringestservice.dao.ListMapConverter;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@Builder
@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "Transactions")
public class Transactions implements Serializable{

    @DynamoDBHashKey(attributeName = "TransactionId")
    @DynamoDBAutoGeneratedKey
    private String transactionId;
    
    @DynamoDBAttribute(attributeName = "CartId")
    private String cartId;

    @DynamoDBAttribute(attributeName = "request")
    @DynamoDBTypeConverted(converter = ListMapConverter.class)
    private Map<String,Object> requestDetails;
    
}
